spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereloadc
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://159.223.79.247:3306/maidoo_final
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: quanla02@ciuz
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: linhpttph16448@fpt.edu.vn
    password: Phamthuylinhlinh2002
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
file:
  upload-dir: D:\\Upload
  max-size: 1024 #MB
jwt:
  secret: maidoo
  refresh-secret: maidoorefreshtoken
  jwtExpirationMs: 86400000


scheduled-delete:
  #  check bill everyday
  bill-delete: 0 0 0 * * ?
server:
  port: 8080
#jasypt:
#  encryptor:
#    algorithm: PBEWithMD5AndDES
#    iv-generator-classname: org.jasypt.iv.NoIvGenerator
